{% set name = "frettipy" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22816969ddb95125ee09c03b3c451e0276d428855e865637c0bac35ab3bd27d2

build:
  entry_points:
    - frettipy = frettipy:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=2.7
    - flit-core >=3.4
    - pip
  run:
    - python >=2.7

test:
  imports:
    - frettipy
  commands:
    - pip check
    - frettipy
  requires:
    - pip

about:
  home: https://github.com/janberges/frettipy
  summary: No fretting about pretty Python
  license: 0BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janberges
