{% set name = "frettipy" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5aac884ba5c73a5a272f3a0df0ed1d54a88f10eaa7b7672e89b5c3859847fbc5

build:
  entry_points:
    - frettipy = frettipy:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=2.7
    - flit-core >=3.4
    - pip
  run:
    - python >=2.7

test:
  imports:
    - frettipy
  commands:
    - pip check
    - frettipy
  requires:
    - pip

about:
  home: https://github.com/janberges/frettipy
  summary: No fretting about pretty Python
  license: 0BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janberges
