{% set name = "frettipy" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15342b1360ea6ab94b53d52e94cc048ad8f1bdef286fd2d683dd6db124afe934

build:
  entry_points:
    - frettipy = frettipy:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - frettipy
  commands:
    - pip check
    - frettipy
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/janberges/frettipy
  summary: No fretting about pretty Python
  license: 0BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janberges
